<Project>
    <PropertyGroup>
        <Authors>weizinai</Authors>
        <PackageLicenseExpression>MIT</PackageLicenseExpression>
        <RepositoryUrl>https://github.com/weizinai/StardewValleyMods</RepositoryUrl>
        <RepositoryType>git</RepositoryType>

        <TargetFramework>net6.0</TargetFramework>
        <Nullable>enable</Nullable>
        <RootNamespace>weizinai.StardewValleyMod.$(MSBuildProjectName)</RootNamespace>
        <EnforceCodeStyleInBuild>true</EnforceCodeStyleInBuild>

        <GamePath>C:\Applications\Steam\steamapps\common\Stardew Valley</GamePath>
        <GameModsPath>$(GamePath)\Mods\weizinai</GameModsPath>
        <ModZipPath>$(MSBuildThisFileDirectory).releases</ModZipPath>
    </PropertyGroup>

    <ItemGroup>
        <Using Alias="SObject" Include="StardewValley.Object"/>
    </ItemGroup>
</Project>